import { faq, quiz, timeline } from './data/electionKnowledge.js';

const chat = document.getElementById('chat');
const chatForm = document.getElementById('chat-form');
const userInput = document.getElementById('user-input');
const timelineEl = document.getElementById('timeline');
const stepsEl = document.getElementById('steps');

const geminiState = {
  apiKey: localStorage.getItem('GEMINI_API_KEY') || '',
  model: 'gemini-1.5-flash'
};

function addMessage(text, cls) {
  const p = document.createElement('p');
  p.className = `msg ${cls}`;
  p.textContent = text;
  chat.appendChild(p);
  chat.scrollTop = chat.scrollHeight;
}

function addSystemTip() {
  if (!geminiState.apiKey) {
    addMessage('Tip: Add your Gemini API key from the top-right button to enable AI answers.', 'bot');
  }
}

function fallbackResponse(text) {
  const t = text.toLowerCase();
  const match = faq.find((item) => item.keys.some((k) => t.includes(k)));
  if (match) return match.answer;
  return 'I can help with registration, timelines, ID, early voting, and absentee process. Ask a specific question to continue.';
}

async function askGemini(text) {
  if (!geminiState.apiKey) return null;
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${geminiState.model}:generateContent?key=${geminiState.apiKey}`;
  const prompt = `You are an Election Process Education assistant. Give concise, practical, neutral guidance. Remind user to verify exact legal deadlines on official election authority websites. User question: ${text}`;
  const body = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: { temperature: 0.3, maxOutputTokens: 300 }
  };

  const res = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });

  if (!res.ok) {
    throw new Error(`Gemini error: ${res.status}`);
  }

  const json = await res.json();
  return json?.candidates?.[0]?.content?.parts?.[0]?.text || null;
}

async function respond(text) {
  try {
    const geminiAnswer = await askGemini(text);
    if (geminiAnswer) return `${geminiAnswer}\n\n(Generated by Gemini)`;
  } catch (err) {
    return `${fallbackResponse(text)}\n\n(Note: Gemini unavailable, using local assistant.)`;
  }

  return fallbackResponse(text);
}

async function handlePrompt(text) {
  addMessage(text, 'user');
  addMessage('Thinking...', 'bot');
  const thinkingNode = chat.lastChild;
  const answer = await respond(text);
  thinkingNode.textContent = answer;
}

chatForm.addEventListener('submit', async (e) => {
  e.preventDefault();
  const text = userInput.value.trim();
  if (!text) return;
  userInput.value = '';
  await handlePrompt(text);
});

document.querySelectorAll('[data-q]').forEach((btn) => {
  btn.addEventListener('click', async () => {
    const q = btn.getAttribute('data-q');
    await handlePrompt(q);
  });
});

document.getElementById('set-key')?.addEventListener('click', () => {
  const key = prompt('Enter Gemini API Key (stored only in your browser localStorage):', geminiState.apiKey || '');
  if (key !== null) {
    geminiState.apiKey = key.trim();
    localStorage.setItem('GEMINI_API_KEY', geminiState.apiKey);
    addMessage(geminiState.apiKey ? 'Gemini key saved.' : 'Gemini key cleared. Using local assistant.', 'bot');
  }
});

timeline.forEach((item) => {
  const li = document.createElement('li');
  li.innerHTML = `<strong>${item.phase}:</strong> ${item.detail}`;
  timelineEl.appendChild(li);
});

document.getElementById('navigator').addEventListener('submit', (e) => {
  e.preventDefault();
  stepsEl.innerHTML = '';
  const registered = document.getElementById('registered').value;
  const mode = document.getElementById('mode').value;
  const id = document.getElementById('id').value;

  const steps = [];
  if (registered === 'no') steps.push('Register to vote through your official election portal.');
  if (registered === 'unsure') steps.push('Verify your voter registration status online before deadlines.');
  if (id !== 'yes') steps.push('Check acceptable voter ID rules and prepare alternate documents if needed.');
  if (mode === 'mail') steps.push('Request a mail/absentee ballot and track request approval status.');
  if (mode === 'early') steps.push('Find your early voting centers and available dates.');
  if (mode === 'in_person') steps.push('Locate your polling station and confirm polling hours.');
  steps.push('Review your sample ballot to reduce errors on election day.');
  steps.push('Verify all local deadlines from official election authority sources.');

  steps.forEach((s) => {
    const li = document.createElement('li');
    li.textContent = s;
    stepsEl.appendChild(li);
  });
});

const quizEl = document.getElementById('quiz');
quiz.forEach((item, i) => {
  const block = document.createElement('div');
  block.innerHTML = `<p><strong>Q${i + 1}.</strong> ${item.q}</p>`;

  item.options.forEach((op, idx) => {
    const id = `q${i}_${idx}`;
    const label = document.createElement('label');
    label.innerHTML = `<input type="radio" name="q${i}" value="${idx}" id="${id}" /> ${op}`;
    block.appendChild(label);
  });

  quizEl.appendChild(block);
});

document.getElementById('grade-quiz').addEventListener('click', () => {
  let score = 0;
  quiz.forEach((q, i) => {
    const selected = document.querySelector(`input[name="q${i}"]:checked`);
    if (selected && Number(selected.value) === q.correct) score += 1;
  });

  document.getElementById('quiz-result').textContent = `You scored ${score}/${quiz.length}.`;
});

addMessage('Hi! I can guide you through election steps and timelines. Ask me anything to start.', 'bot');
addSystemTip();
