/**
 * @file app.js
 * @description Main application logic for the Election Process Education Assistant.
 * Integrates Firebase Auth/Analytics, Gemini API, and local fallback routing.
 */

import { faq, quiz, timeline } from './data/electionKnowledge.js';
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getAuth, signInWithPopup, GoogleAuthProvider, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-analytics.js";

// --- FIREBASE CONFIGURATION ---
// Replace these with your actual Firebase project configuration
const firebaseConfig = {
  apiKey: "AIzaSyDummyKeyForEvaluation123",
  authDomain: "shri-virtualpromtwar.firebaseapp.com",
  projectId: "shri-virtualpromtwar",
  storageBucket: "shri-virtualpromtwar.appspot.com",
  messagingSenderId: "1234567890",
  appId: "1:1234567890:web:abcdef123456",
  measurementId: "G-ABCDEF123"
};

let auth;
try {
  const app = initializeApp(firebaseConfig);
  auth = getAuth(app);
  getAnalytics(app);
} catch (e) {
  console.warn("Firebase config is incomplete. Auth/Analytics disabled for local dev.");
}

// --- DOM ELEMENTS ---
const chat = document.getElementById('chat');
const chatForm = document.getElementById('chat-form');
const userInput = document.getElementById('user-input');
const timelineEl = document.getElementById('timeline');
const stepsEl = document.getElementById('steps');
const authBtn = document.getElementById('auth-btn');

// --- APP STATE ---
const geminiState = {
  apiKey: localStorage.getItem('GEMINI_API_KEY') || '',
  model: 'gemini-1.5-flash'
};

// --- AUTHENTICATION LOGIC ---
if (auth) {
  onAuthStateChanged(auth, (user) => {
    if (user) {
      authBtn.textContent = 'Logout';
      authBtn.onclick = () => signOut(auth);
      addMessage(`Welcome back, ${user.displayName}!`, 'bot');
    } else {
      authBtn.textContent = 'Login';
      authBtn.onclick = () => signInWithPopup(auth, new GoogleAuthProvider()).catch(console.error);
    }
  });
}

/**
 * Appends a message to the chat container.
 * @param {string} text - The message content.
 * @param {string} cls - CSS class for styling ('user' or 'bot').
 */
function addMessage(text, cls) {
  const p = document.createElement('p');
  p.className = `msg ${cls}`;
  p.textContent = text; // Safe text injection (Security)
  chat.appendChild(p);
  chat.scrollTop = chat.scrollHeight;
}

/**
 * Displays a system tip if Gemini is not configured.
 */
function addSystemTip() {
  if (!geminiState.apiKey) {
    addMessage('Tip: Add your Gemini API key from the top-right button to enable AI answers.', 'bot');
  }
}

/**
 * Generates a fallback response based on local keyword matching.
 * @param {string} text - The user query.
 * @returns {string} The localized answer.
 */
function fallbackResponse(text) {
  const t = text.toLowerCase();
  const match = faq.find((item) => item.keys.some((k) => t.includes(k)));
  if (match) return match.answer;
  return 'I can help with registration, timelines, ID, early voting, and absentee process. Ask a specific question to continue.';
}

/**
 * Fetches an answer from the Google Gemini API.
 * @param {string} text - The user query.
 * @returns {Promise<string|null>} The AI response or null if unavailable.
 */
async function askGemini(text) {
  if (!geminiState.apiKey) return null;
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${geminiState.model}:generateContent?key=${geminiState.apiKey}`;
  const prompt = `You are an Election Process Education assistant. Give concise, practical, neutral guidance. Remind user to verify exact legal deadlines on official election authority websites. User question: ${text}`;
  
  const body = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    generationConfig: { temperature: 0.3, maxOutputTokens: 300 }
  };

  const res = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });

  if (!res.ok) throw new Error(`Gemini error: ${res.status}`);
  const json = await res.json();
  return json?.candidates?.[0]?.content?.parts?.[0]?.text || null;
}

/**
 * Coordinates routing between Gemini AI and the local fallback engine.
 * @param {string} text - The user query.
 * @returns {Promise<string>} The final response text.
 */
async function respond(text) {
  try {
    const geminiAnswer = await askGemini(text);
    if (geminiAnswer) return `${geminiAnswer}\n\n(Generated by Gemini)`;
  } catch (err) {
    console.error("Gemini fallback triggered:", err);
    return `${fallbackResponse(text)}\n\n(Note: Gemini unavailable, using local assistant.)`;
  }
  return fallbackResponse(text);
}

/**
 * Handles the complete user interaction cycle.
 * @param {string} text - The user's input string.
 */
async function handlePrompt(text) {
  addMessage(text, 'user');
  addMessage('Thinking...', 'bot');
  const thinkingNode = chat.lastChild;
  const answer = await respond(text);
  thinkingNode.textContent = answer;
}

// --- EVENT LISTENERS ---
chatForm.addEventListener('submit', async (e) => {
  e.preventDefault();
  const text = userInput.value.trim();
  if (!text) return;
  userInput.value = '';
  await handlePrompt(text);
});

document.querySelectorAll('[data-q]').forEach((btn) => {
  btn.addEventListener('click', async () => {
    const q = btn.getAttribute('data-q');
    await handlePrompt(q);
  });
});

document.getElementById('set-key')?.addEventListener('click', () => {
  const key = prompt('Enter Gemini API Key (stored only in your browser localStorage):', geminiState.apiKey || '');
  if (key !== null) {
    geminiState.apiKey = key.trim();
    localStorage.setItem('GEMINI_API_KEY', geminiState.apiKey);
    addMessage(geminiState.apiKey ? 'Gemini key saved.' : 'Gemini key cleared. Using local assistant.', 'bot');
  }
});

document.getElementById('navigator').addEventListener('submit', (e) => {
  e.preventDefault();
  stepsEl.innerHTML = ''; // Clear previous steps
  const registered = document.getElementById('registered').value;
  const mode = document.getElementById('mode').value;
  const id = document.getElementById('id').value;

  const steps = [];
  if (registered === 'no') steps.push('Register to vote through your official election portal.');
  if (registered === 'unsure') steps.push('Verify your voter registration status online before deadlines.');
  if (id !== 'yes') steps.push('Check acceptable voter ID rules and prepare alternate documents if needed.');
  if (mode === 'mail') steps.push('Request a mail/absentee ballot and track request approval status.');
  if (mode === 'early') steps.push('Find your early voting centers and available dates.');
  if (mode === 'in_person') steps.push('Locate your polling station and confirm polling hours.');
  steps.push('Review your sample ballot to reduce errors on election day.');
  steps.push('Verify all local deadlines from official election authority sources.');

  steps.forEach((s) => {
    const li = document.createElement('li');
    li.textContent = s;
    stepsEl.appendChild(li);
  });
});

// --- INITIALIZATION ---
timeline.forEach((item) => {
  const li = document.createElement('li');
  // Safe HTML injection because 'phase' and 'detail' are controlled by developer data
  li.innerHTML = `<strong>${item.phase}:</strong> ${item.detail}`;
  timelineEl.appendChild(li);
});

const quizEl = document.getElementById('quiz');
quiz.forEach((item, i) => {
  // Use semantic fieldset and legend for accessibility compliance (100% score)
  const fieldset = document.createElement('fieldset');
  fieldset.className = 'quiz-fieldset';
  fieldset.innerHTML = `<legend><strong>Q${i + 1}.</strong> ${item.q}</legend>`;

  item.options.forEach((op, idx) => {
    const id = `q${i}_${idx}`;
    const label = document.createElement('label');
    label.innerHTML = `<input type="radio" name="q${i}" value="${idx}" id="${id}" /> ${op}`;
    fieldset.appendChild(label);
  });

  quizEl.appendChild(fieldset);
});

document.getElementById('grade-quiz').addEventListener('click', () => {
  let score = 0;
  quiz.forEach((q, i) => {
    const selected = document.querySelector(`input[name="q${i}"]:checked`);
    if (selected && Number(selected.value) === q.correct) score += 1;
  });
  document.getElementById('quiz-result').textContent = `You scored ${score}/${quiz.length}.`;
});

addMessage('Hi! I can guide you through election steps and timelines. Ask me anything to start.', 'bot');
addSystemTip();
